### ISSUE TITLE
can't recalculate entropy

### ISSUE THREAD

**Issue by Hoernchen** [satyapravin/StructuralEntropy#1]
Hi,
I'm currently trying to run your "Hedging long only portfolio using structural entropy" notebook, but I can't recalculate the structural entropy using your data, the data does not look like the embedded "smooth" entropy.zip at all and all values appears to be too small (?):
```
entropy_df3 = structural_entropy(data.fillna(0), lags=[60])
entropy_df3['60'].plot(figsize=(15, 8))
```
![image](https://github.com/satyapravin/StructuralEntropy/assets/2532692/b49d9796-dddb-4bd7-bd6d-8b9fffcd4d08)

What am I missing?

Plotting the supplied entropy.zip:
```
entropy_df = pd.read_csv('entropy.zip', header=0, index_col=0, parse_dates=True).dropna() 
entropy_df['60'].plot(figsize=(15, 8))
```
![image](https://github.com/satyapravin/StructuralEntropy/assets/2532692/f4afc682-c49f-4e08-b484-944bcf546ea8)

**Comment by satyapravin** [comment]
Take entropy of returns and not data.

**Comment by satyapravin** [comment]
entropy_df3 = structural_entropy(returns, lags=[60])

**Comment by Hoernchen** [comment]
Oh, yeah, that works, thanks!

I was misled by the line
```
#entropy_df = structural_entropy(data, lags=[120, 110, 105, 100, 95, 90, 85, 80, 75, 70, 65, 60])
```
in your notebook...
